/* ═══════════════════════════════════════════════════════════════
   THE DRY DOWN — Fragrance Note Encyclopedia
   100+ notes with descriptions, categories, origins & images
   ═══════════════════════════════════════════════════════════════ */

const NOTE_ENCYCLOPEDIA = {
  // ── WOODS ──
  "oud": { description: "Also known as agarwood, oud is formed when Aquilaria trees become infected with mold. The resulting resin creates one of the most prized and expensive raw materials in perfumery — smoky, animalic, and deeply complex. It's the backbone of Middle Eastern perfumery and has become a global luxury staple.", category: "Wood", origin: "Southeast Asia, Middle East", image: "https://images.unsplash.com/photo-1600857544200-b2f666a9a2ec?w=600&h=400&fit=crop&q=80" },
  "sandalwood": { description: "Creamy, warm, and milky — sandalwood is one of the most versatile base notes. Mysore sandalwood from India is considered the finest, offering a rich, buttery aroma. Australian sandalwood is now more commonly used due to sustainability concerns. It blends beautifully with nearly everything.", category: "Wood", origin: "India, Australia", image: "https://images.unsplash.com/photo-1501004318855-6e929e2e3a42?w=600&h=400&fit=crop&q=80" },
  "cedar": { description: "Clean, dry, and pencil-shaving woody. Virginia cedar is sharp and dry, while Atlas cedar is warmer and more aromatic. Cedar is a foundational woody note that adds structure and a natural crispness to fragrances without being overpowering.", category: "Wood", origin: "North America, Morocco", image: "https://images.unsplash.com/photo-1542273917363-3b1817f69a2d?w=600&h=400&fit=crop&q=80" },
  "cedarwood": { description: "A broader term encompassing various cedar species used in perfumery. Cedarwood essential oil provides a warm, balsamic woodiness that forms the backbone of many masculine and unisex compositions. It adds longevity and a natural elegance.", category: "Wood", origin: "North America, Morocco, Virginia", image: "https://images.unsplash.com/photo-1425913397330-cf8af2ff7b89?w=600&h=400&fit=crop&q=80" },
  "vetiver": { description: "Earthy, smoky, and green with a grounding quality. Haitian vetiver is smoky and deep, while Javanese vetiver is cleaner. Distilled from the roots of a tropical grass, it adds sophistication and depth. Often called 'the oil of tranquility.'", category: "Wood", origin: "Haiti, Java, India", image: "https://images.unsplash.com/photo-1509587584298-0f3b3a3a1797?w=600&h=400&fit=crop&q=80" },
  "guaiac wood": { description: "Smoky, creamy, and slightly sweet with tea-like nuances. Guaiac wood (also spelled gaiac) comes from the Palo Santo tree family and adds a distinctive smoky-woody character that bridges the gap between incense and clean woods.", category: "Wood", origin: "South America", image: "https://images.unsplash.com/photo-1473448912268-2022ce9509d8?w=600&h=400&fit=crop&q=80" },
  "birch": { description: "Smoky, leathery, and tarry. Birch tar was historically used to create leather accords in perfumery. It gives fragrances a rugged, outdoorsy character with a campfire-like smokiness. Key ingredient in classic Russian Leather compositions.", category: "Wood", origin: "Northern Europe, Russia", image: "https://images.unsplash.com/photo-1588392382834-a891154bca4d?w=600&h=400&fit=crop&q=80" },
  "cypress": { description: "Fresh, clean, and slightly resinous with a green, coniferous character. Cypress adds a Mediterranean freshness to compositions, evoking windswept coastal landscapes. It sits beautifully between aromatic herbs and woods.", category: "Wood", origin: "Mediterranean, Southern Europe", image: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=600&h=400&fit=crop&q=80" },
  "driftwood": { description: "A modern perfumery concept that evokes sun-bleached, salt-washed wood. Driftwood accords combine woody, marine, and mineral facets to create a sense of weathered coastal landscapes and ocean-kissed timber.", category: "Wood", origin: "Synthetic accord", image: "https://images.unsplash.com/photo-1501785888041-af3ef285b470?w=600&h=400&fit=crop&q=80" },
  "bamboo": { description: "Clean, green, and airy with a fresh woody character. Bamboo in perfumery creates a light, transparent woodiness that feels modern and minimalist. It adds a zen-like calm and fresh green quality.", category: "Wood", origin: "Asia", image: "https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=600&h=400&fit=crop&q=80" },
  "teak": { description: "Rich, warm, and slightly honeyed with a luxurious woody character. Teak evokes fine furniture and exotic interiors. In perfumery, it adds a sophisticated warmth that feels both natural and refined.", category: "Wood", origin: "Southeast Asia", image: "https://images.unsplash.com/photo-1558603668-6570496b66f8?w=600&h=400&fit=crop&q=80" },
  "ebony": { description: "Dark, dense, and deeply woody with a smooth, polished quality. Ebony in perfumery creates an impression of dark, precious wood — sophisticated and mysterious with an almost lacquered finish.", category: "Wood", origin: "Tropical regions", image: "https://images.unsplash.com/photo-1558603668-6570496b66f8?w=600&h=400&fit=crop&q=80" },

  // ── FLORALS ──
  "rose": { description: "The queen of flowers in perfumery. Different varieties — Turkish, Bulgarian, Damascene, Taifi, Centifolia — each bring distinct facets from honeyed and jammy to fresh and dewy. Rose is endlessly versatile, appearing in everything from fresh colognes to deep orientals.", category: "Floral", origin: "Turkey, Bulgaria, Morocco, Saudi Arabia", image: "https://images.unsplash.com/photo-1455659817273-f96807779a8a?w=600&h=400&fit=crop&q=80" },
  "jasmine": { description: "Rich, intoxicating, and narcotic. Jasmine is one of the most important floral notes in perfumery, adding sensuality and depth. Jasmine Sambac is sweeter and more tropical, while Jasmine Grandiflorum is more classical and heady.", category: "Floral", origin: "India, Egypt, Morocco", image: "https://images.unsplash.com/photo-1587727005224-82e3d9e0b3a6?w=600&h=400&fit=crop&q=80" },
  "iris": { description: "Powdery, elegant, and expensive. Iris (orris root) is one of the most costly perfume ingredients, requiring up to seven years of aging. It adds a sophisticated, lipstick-like powdery quality that's unmistakable in high-end perfumery.", category: "Floral", origin: "Italy, Morocco", image: "https://images.unsplash.com/photo-1585386959984-a4155224a1ad?w=600&h=400&fit=crop&q=80" },
  "tuberose": { description: "Intensely heady, creamy, and narcotic. Tuberose is one of the most powerful white florals, adding a rich, almost buttery quality. It's both beautiful and animalic — a flower that demands attention and dominates any composition.", category: "Floral", origin: "India, Morocco", image: "https://images.unsplash.com/photo-1468327768560-75b778cbb551?w=600&h=400&fit=crop&q=80" },
  "lily": { description: "Clean, fresh, and dewy with a waxy sweetness. Lily of the valley (muguet) is one of the most popular floral notes in perfumery. Since it can't be naturally extracted, it's always recreated synthetically, adding a bright, spring-like freshness.", category: "Floral", origin: "Synthetic recreation", image: "https://images.unsplash.com/photo-1490750967868-88aa4f44baee?w=600&h=400&fit=crop&q=80" },
  "lily of the valley": { description: "A bright, green, dewy floral that captures the essence of spring. One of the few flowers whose scent cannot be extracted naturally, so perfumers recreate it synthetically. It adds an innocent, fresh, clean quality to compositions.", category: "Floral", origin: "Synthetic recreation", image: "https://images.unsplash.com/photo-1589994160839-163cd867cfe8?w=600&h=400&fit=crop&q=80" },
  "orange blossom": { description: "Sweet, honeyed, and narcotic with a waxy green facet. Orange blossom (neroli from the flowers, petit grain from the leaves) is one of the most beloved florals. It's the heart of many classic colognes and oriental fragrances.", category: "Floral", origin: "Morocco, Tunisia, South of France", image: "https://images.unsplash.com/photo-1557800636-894a64c1696f?w=600&h=400&fit=crop&q=80" },
  "magnolia": { description: "Lush, creamy, and lemony with a champagne-like effervescence. Magnolia adds a bright, sophisticated floral quality that feels both fresh and luxurious. It's less heavy than jasmine but more complex than simple white florals.", category: "Floral", origin: "China, Americas", image: "https://images.unsplash.com/photo-1558171813-4c088753af8f?w=600&h=400&fit=crop&q=80" },
  "ylang ylang": { description: "Rich, exotic, and intensely sweet with banana-like and custard facets. Ylang ylang is a tropical flower used extensively in oriental and floral perfumes. Different distillation grades (Extra, I, II, III) offer varying intensities.", category: "Floral", origin: "Comoros Islands, Madagascar", image: "https://images.unsplash.com/photo-1490750967868-88aa4f44baee?w=600&h=400&fit=crop&q=80" },
  "peony": { description: "Soft, fresh, and rosy with a hint of green and watermelon. Peony adds a delicate, feminine floral quality that's lighter than rose but more complex than simple clean florals. Popular in modern, youthful fragrances.", category: "Floral", origin: "China, Europe", image: "https://images.unsplash.com/photo-1459262838948-3e2de6c1ec80?w=600&h=400&fit=crop&q=80" },
  "orchid": { description: "Exotic, powdery, and creamy with a velvety richness. Orchid notes in perfumery are typically synthetic recreations that evoke luxury and sensuality. They add a refined, sophisticated floral quality.", category: "Floral", origin: "Synthetic accord", image: "https://images.unsplash.com/photo-1567696911980-2eed69a46042?w=600&h=400&fit=crop&q=80" },
  "violet": { description: "Powdery, sweet, and slightly green. Violet has a unique ability to 'disappear' from your perception due to ionone compounds. Violet leaf is greener and crisper, while violet flower is sweeter and more powdery.", category: "Floral", origin: "Egypt, France", image: "https://images.unsplash.com/photo-1457089328109-e5d9bd499191?w=600&h=400&fit=crop&q=80" },
  "gardenia": { description: "Lush, creamy, and tropical with a buttery richness. Gardenia is one of the most beautiful white florals — heady and intoxicating without being as heavy as tuberose. It adds a luxurious, velvety quality.", category: "Floral", origin: "China, Japan", image: "https://images.unsplash.com/photo-1468327768560-75b778cbb551?w=600&h=400&fit=crop&q=80" },
  "freesia": { description: "Light, peppery, and fresh with a clean, zesty character. Freesia adds brightness and a subtle spicy-floral accent to compositions. It's a popular heart note in fresh and clean fragrances.", category: "Floral", origin: "South Africa", image: "https://images.unsplash.com/photo-1457089328109-e5d9bd499191?w=600&h=400&fit=crop&q=80" },
  "geranium": { description: "Green, rosy, and slightly minty with a citrusy brightness. Geranium is a versatile note that bridges floral and aromatic categories. Egyptian geranium is considered the finest quality, adding natural elegance.", category: "Floral", origin: "Egypt, Réunion", image: "https://images.unsplash.com/photo-1457089328109-e5d9bd499191?w=600&h=400&fit=crop&q=80" },
  "plumeria": { description: "Exotic, creamy, and tropical with hints of jasmine and citrus. Also known as frangipani, this Hawaiian flower adds a lush, tropical floral quality that evokes island paradise and warm ocean breezes.", category: "Floral", origin: "Pacific Islands, Caribbean", image: "https://images.unsplash.com/photo-1501004318855-6e929e2e3a42?w=600&h=400&fit=crop&q=80" },
  "heliotrope": { description: "Powdery, almond-like, and vanillic with a cherry-pie sweetness. Heliotrope bridges the floral and gourmand worlds, adding a soft, comforting quality that's both elegant and cozy.", category: "Floral", origin: "Peru, Mediterranean", image: "https://images.unsplash.com/photo-1457089328109-e5d9bd499191?w=600&h=400&fit=crop&q=80" },
  "neroli": { description: "Fresh, sparkling, and green-floral with a honeyed depth. Distilled from bitter orange blossoms, neroli is one of the finest citrus-floral ingredients. It's the heart of classic Eau de Cologne and adds sophisticated freshness.", category: "Floral", origin: "Tunisia, Morocco, Egypt", image: "https://images.unsplash.com/photo-1557800636-894a64c1696f?w=600&h=400&fit=crop&q=80" },

  // ── CITRUS ──
  "bergamot": { description: "A citrus fruit that provides the bright, slightly bitter, aromatic opening found in many fragrances. It's the backbone of Earl Grey tea's distinctive flavor and the cornerstone ingredient of classic Eau de Cologne.", category: "Citrus", origin: "Calabria, Italy", image: "https://images.unsplash.com/photo-1611080626919-7cf5a9dbab5b?w=600&h=400&fit=crop&q=80" },
  "lemon": { description: "Bright, zesty, and immediately uplifting. Lemon is one of the most universally recognized citrus notes, adding a clean, sparkling freshness to openings. Sicilian lemon is the most prized variety in perfumery.", category: "Citrus", origin: "Sicily, Italy", image: "https://images.unsplash.com/photo-1590502593747-42a996133562?w=600&h=400&fit=crop&q=80" },
  "mandarin orange": { description: "Sweet, juicy, and bright with a slightly tangy, rounded character. Mandarin is softer and sweeter than other citrus notes, making it perfect for adding a gentle, approachable freshness to fragrances.", category: "Citrus", origin: "Southern Europe, Brazil", image: "https://images.unsplash.com/photo-1547514701-42fee21e7a3e?w=600&h=400&fit=crop&q=80" },
  "grapefruit": { description: "Tart, sparkling, and slightly bitter with a pink, juicy quality. Grapefruit adds an energetic, modern freshness. The nootkatone compound gives it a distinctive character that lasts longer than most citrus notes.", category: "Citrus", origin: "Caribbean, Americas", image: "https://images.unsplash.com/photo-1577234286642-fc512a5f8f11?w=600&h=400&fit=crop&q=80" },
  "lime": { description: "Sharp, green, and effervescent with a cocktail-like brightness. Lime adds an upbeat, slightly tropical freshness. Both Persian lime and kaffir lime are used, each offering different facets from zesty to aromatic.", category: "Citrus", origin: "Southeast Asia, Mexico", image: "https://images.unsplash.com/photo-1546559321-4b38c7743795?w=600&h=400&fit=crop&q=80" },
  "orange": { description: "Sweet, juicy, and sunny. Sweet orange adds a warm, rounded citrus character that's less sharp than lemon and less bitter than bergamot. It's inviting and universally appealing, often used in fresh and gourmand compositions.", category: "Citrus", origin: "Mediterranean, Brazil", image: "https://images.unsplash.com/photo-1582979512210-99b6a53386f9?w=600&h=400&fit=crop&q=80" },
  "yuzu": { description: "Tart, green, and aromatic with a distinctive Japanese character. Yuzu is more complex than other citrus notes — slightly floral, herbaceous, and with an almost grapefruit-like bitterness. A favorite in niche perfumery.", category: "Citrus", origin: "Japan, Korea", image: "https://images.unsplash.com/photo-1590502593747-42a996133562?w=600&h=400&fit=crop&q=80" },
  "bitter orange": { description: "More complex than sweet orange with a dry, aromatic, slightly medicinal quality. Bitter orange peel is used to create bigarade oil, a classic perfumery ingredient that adds sophistication and depth to citrus accords.", category: "Citrus", origin: "Mediterranean, North Africa", image: "https://images.unsplash.com/photo-1582979512210-99b6a53386f9?w=600&h=400&fit=crop&q=80" },

  // ── SPICES ──
  "saffron": { description: "One of the most expensive spices in the world, saffron adds a warm, honeyed, leathery quality to fragrances. It's a signature note in many Middle Eastern perfumes and adds instant richness, exoticism, and depth.", category: "Spice", origin: "Iran, Kashmir", image: "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=600&h=400&fit=crop&q=80" },
  "pink pepper": { description: "Bright, spicy, and slightly fruity with a rosy sparkle. Not actually related to black pepper — it comes from the Schinus molle tree. Pink pepper adds a modern, lively sparkle to openings that's become a signature of contemporary niche perfumery.", category: "Spice", origin: "South America", image: "https://images.unsplash.com/photo-1532336414038-cf19250c5757?w=600&h=400&fit=crop&q=80" },
  "black pepper": { description: "Sharp, warm, and biting with a dry, woody-spicy character. Black pepper adds energy and a masculine edge to compositions. It creates a tingling, almost effervescent sensation in fragrance openings.", category: "Spice", origin: "India, Vietnam", image: "https://images.unsplash.com/photo-1532336414038-cf19250c5757?w=600&h=400&fit=crop&q=80" },
  "pepper": { description: "Warm, sharp, and energetic. Pepper in perfumery can refer to black, white, pink, or Sichuan varieties, each contributing different facets from dry heat to fruity sparkle. It adds life and vibrancy to compositions.", category: "Spice", origin: "India, Southeast Asia", image: "https://images.unsplash.com/photo-1532336414038-cf19250c5757?w=600&h=400&fit=crop&q=80" },
  "cardamom": { description: "Aromatic, warm, and slightly eucalyptus-like with a fresh, green spiciness. Cardamom is the bridge between fresh and spicy, adding an exotic warmth that's never heavy. A key ingredient in many modern masculine fragrances.", category: "Spice", origin: "Guatemala, India", image: "https://images.unsplash.com/photo-1599909533601-29b0b6cbf2f3?w=600&h=400&fit=crop&q=80" },
  "cinnamon": { description: "Warm, sweet, and spicy with a cozy, festive quality. Cinnamon bark oil is more complex and less sweet than cassia. In perfumery, it adds a comforting warmth that pairs beautifully with vanilla, amber, and florals.", category: "Spice", origin: "Sri Lanka, Indonesia", image: "https://images.unsplash.com/photo-1528301721190-186c3bd85418?w=600&h=400&fit=crop&q=80" },
  "ginger": { description: "Fresh, zesty, and warm with a citrusy bite. Ginger adds an energetic, slightly lemony spiciness that bridges citrus and spice categories. It's invigorating and adds movement to compositions.", category: "Spice", origin: "Southeast Asia, Jamaica", image: "https://images.unsplash.com/photo-1615485290382-441e4d049cb5?w=600&h=400&fit=crop&q=80" },
  "nutmeg": { description: "Warm, sweet, and slightly narcotic with a cozy, balsamic quality. Nutmeg adds a sophisticated spiciness that's more refined than cinnamon. It's often used in small doses to add depth and warmth.", category: "Spice", origin: "Indonesia, Grenada", image: "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=600&h=400&fit=crop&q=80" },
  "clove": { description: "Warm, spicy, and slightly medicinal with an intense, rich character. Eugenol, clove's main component, adds a powerful warm spiciness. It's used carefully in perfumery to add depth without overwhelming.", category: "Spice", origin: "Indonesia, Madagascar", image: "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=600&h=400&fit=crop&q=80" },
  "star anise": { description: "Sweet, licorice-like, and aromatic with a warm, comforting quality. Star anise adds an exotic, slightly mysterious spiciness. Its anethole content gives it a distinctive sweetness that works in both oriental and fresh compositions.", category: "Spice", origin: "China, Vietnam", image: "https://images.unsplash.com/photo-1517668808822-9ebb02f2a0e6?w=600&h=400&fit=crop&q=80" },
  "cumin": { description: "Warm, earthy, and slightly animalic with a musky, skin-like quality. Cumin is used very carefully in perfumery — in small doses it adds an intriguing, sensual warmth that mimics body heat. Too much becomes overpowering.", category: "Spice", origin: "Middle East, India", image: "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=600&h=400&fit=crop&q=80" },

  // ── GOURMAND ──
  "vanilla": { description: "Derived from the vanilla orchid, this warm, sweet, creamy note is one of the most universally loved in perfumery. It adds comfort, sweetness, and sensuality. Madagascar Bourbon vanilla is considered the finest quality.", category: "Gourmand", origin: "Madagascar, Tahiti, Mexico", image: "https://images.unsplash.com/photo-1631206753348-db44968fd440?w=600&h=400&fit=crop&q=80" },
  "tonka bean": { description: "Sweet, warm, and almond-like with hints of vanilla and caramel. Tonka bean contains coumarin, which gives it a distinctive warm, hay-like sweetness. It's become a modern perfumery staple, adding depth without being as sweet as vanilla.", category: "Gourmand", origin: "Venezuela, Brazil", image: "https://images.unsplash.com/photo-1599909533601-29b0b6cbf2f3?w=600&h=400&fit=crop&q=80" },
  "coffee": { description: "Rich, roasted, and slightly bitter. Coffee adds a gourmand warmth and modern edge to fragrances, pairing beautifully with vanilla, leather, and spices. It creates an addictive, energizing quality.", category: "Gourmand", origin: "Ethiopia, Colombia, Brazil", image: "https://images.unsplash.com/photo-1447933601403-0c6688de566e?w=600&h=400&fit=crop&q=80" },
  "chocolate": { description: "Rich, bitter-sweet, and indulgent. Chocolate notes in perfumery range from dark and bitter cocoa to sweet milk chocolate. They add a decadent, cozy warmth that's irresistibly comforting.", category: "Gourmand", origin: "Central America, West Africa", image: "https://images.unsplash.com/photo-1481391319762-47dff72954d9?w=600&h=400&fit=crop&q=80" },
  "caramel": { description: "Buttery, sweet, and golden with a toffee-like warmth. Caramel adds a luscious gourmand quality that evokes burnt sugar and candy. It's often used alongside vanilla and tonka to create rich, cozy base accords.", category: "Gourmand", origin: "Synthetic accord", image: "https://images.unsplash.com/photo-1574085733277-851d9d856a3a?w=600&h=400&fit=crop&q=80" },
  "honey": { description: "Golden, warm, and animalic with a waxy, sweet richness. Natural honey absolute has a complex, slightly dirty sweetness. In perfumery, it bridges gourmand and animalic categories, adding a primal warmth.", category: "Gourmand", origin: "Various", image: "https://images.unsplash.com/photo-1587049352846-4a222e784d38?w=600&h=400&fit=crop&q=80" },
  "coconut": { description: "Tropical, creamy, and sweet with a sunscreen-like warmth. Coconut adds a beachy, vacation quality to fragrances. It pairs beautifully with vanilla, tiare flower, and woody notes for tropical compositions.", category: "Gourmand", origin: "Tropical regions", image: "https://images.unsplash.com/photo-1550317138-10000687a72b?w=600&h=400&fit=crop&q=80" },
  "almond": { description: "Nutty, sweet, and slightly bitter with a marzipan-like quality. Bitter almond adds a sophisticated sweetness, while sweet almond is creamier. The benzaldehyde compound gives it a distinctive cherry-like facet.", category: "Gourmand", origin: "Mediterranean, Middle East", image: "https://images.unsplash.com/photo-1508061253366-f7da158b6d46?w=600&h=400&fit=crop&q=80" },
  "praline": { description: "Caramelized, nutty, and rich with a candy-shop sweetness. Praline notes add a sophisticated gourmand quality that's less simple than plain vanilla or sugar. It evokes indulgence and warmth.", category: "Gourmand", origin: "Synthetic accord", image: "https://images.unsplash.com/photo-1574085733277-851d9d856a3a?w=600&h=400&fit=crop&q=80" },
  "marshmallow": { description: "Soft, pillowy, and sugary with an airy, fluffy sweetness. Marshmallow adds a comforting, cloud-like quality to fragrances. It's lighter than vanilla and creates a cozy, skin-scent effect.", category: "Gourmand", origin: "Synthetic accord", image: "https://images.unsplash.com/photo-1514508694573-9fa6e2b59a75?w=600&h=400&fit=crop&q=80" },
  "toffee": { description: "Rich, buttery, and deeply sweet with a caramelized warmth. Toffee adds a sophisticated, candy-like quality that's darker and more complex than simple sugar notes.", category: "Gourmand", origin: "Synthetic accord", image: "https://images.unsplash.com/photo-1574085733277-851d9d856a3a?w=600&h=400&fit=crop&q=80" },

  // ── RESINS & BALSAMS ──
  "amber": { description: "Not a single ingredient but a blend typically made from labdanum, benzoin, and vanilla. Amber adds warmth, sweetness, and a golden, resinous quality to the base of a fragrance. It's the cornerstone of the oriental fragrance family.", category: "Resin", origin: "Blend of natural resins", image: "https://images.unsplash.com/photo-1518770660439-4636190af475?w=600&h=400&fit=crop&q=80" },
  "incense": { description: "Smoky, sacred, and meditative. Incense notes evoke temples and ceremony, adding a mystical, resinous quality. Olibanum (frankincense) is the most classic incense material, though myrrh and copal are also used.", category: "Resin", origin: "Oman, Somalia, Ethiopia", image: "https://images.unsplash.com/photo-1505236858219-8359eb29e329?w=600&h=400&fit=crop&q=80" },
  "frankincense": { description: "Sacred, citrusy, and resinous with a clean, almost lemony facet. Frankincense (olibanum) is one of the oldest perfume materials, used for thousands of years. Omani frankincense is considered the finest grade.", category: "Resin", origin: "Oman, Somalia", image: "https://images.unsplash.com/photo-1505236858219-8359eb29e329?w=600&h=400&fit=crop&q=80" },
  "myrrh": { description: "Warm, balsamic, and slightly medicinal with a dry, resinous depth. Myrrh has been treasured since ancient Egypt and adds a dark, mysterious quality. It's more somber and earthy than frankincense.", category: "Resin", origin: "Somalia, Ethiopia, Yemen", image: "https://images.unsplash.com/photo-1505236858219-8359eb29e329?w=600&h=400&fit=crop&q=80" },
  "benzoin": { description: "Sweet, warm, and vanilla-like with a balsamic, slightly powdery quality. Benzoin resin adds a soft, cozy sweetness to base accords. Siam benzoin is sweeter, while Sumatra benzoin is more spicy and earthy.", category: "Resin", origin: "Laos, Thailand, Indonesia", image: "https://images.unsplash.com/photo-1518770660439-4636190af475?w=600&h=400&fit=crop&q=80" },
  "labdanum": { description: "Dark, animalic, and amber-like with a leathery, honeyed richness. Harvested from rockrose bushes, labdanum is the primary ingredient in amber accords. It adds a deep, warm, almost animal-like sweetness.", category: "Resin", origin: "Mediterranean", image: "https://images.unsplash.com/photo-1518770660439-4636190af475?w=600&h=400&fit=crop&q=80" },
  "olibanum": { description: "The resin of frankincense — clean, lemony, and resinous with a sacred, meditative quality. Olibanum adds both transparency and depth simultaneously, making it a uniquely versatile ingredient.", category: "Resin", origin: "Oman, Somalia", image: "https://images.unsplash.com/photo-1505236858219-8359eb29e329?w=600&h=400&fit=crop&q=80" },
  "elemi": { description: "Fresh, citrusy, and resinous with a peppery, slightly dill-like quality. Elemi adds a bright, lively facet to resinous and incense compositions, preventing them from becoming too dark.", category: "Resin", origin: "Philippines", image: "https://images.unsplash.com/photo-1518770660439-4636190af475?w=600&h=400&fit=crop&q=80" },

  // ── MUSKS & ANIMALICS ──
  "musk": { description: "Originally from the musk deer, modern musks are synthetic and come in many varieties — white musk (clean, soapy), skin musk (warm, intimate), and animalic musk (sensual, deep). Musk is the invisible foundation of most perfumes.", category: "Animalic", origin: "Synthetic (historically from musk deer)", image: "https://images.unsplash.com/photo-1541643600914-78b084683601?w=600&h=400&fit=crop&q=80" },
  "white musk": { description: "Clean, soapy, and soft with a laundry-fresh quality. White musk is a family of synthetic musks that create a clean, cozy skin scent. It's the backbone of many 'clean' and 'fresh' fragrances.", category: "Animalic", origin: "Synthetic", image: "https://images.unsplash.com/photo-1517263904808-5dc91e3e7044?w=600&h=400&fit=crop&q=80" },
  "leather": { description: "Smoky, animalic, and luxurious. Leather notes in perfumery range from clean suede to dark, tarry birch tar. Leather accords add sophistication, sensuality, and a sense of luxury. Key in fougère and chypre families.", category: "Animalic", origin: "Synthetic accords, birch tar", image: "https://images.unsplash.com/photo-1473188588951-f4b4b6560e4f?w=600&h=400&fit=crop&q=80" },
  "suede": { description: "Soft, powdery, and velvety with a gentle, tactile warmth. Suede is a lighter, more feminine take on leather — it evokes soft textures and quiet luxury rather than rugged masculinity.", category: "Animalic", origin: "Synthetic accord", image: "https://images.unsplash.com/photo-1473188588951-f4b4b6560e4f?w=600&h=400&fit=crop&q=80" },
  "ambergris": { description: "Marine, salty, and sweet with a unique oceanic warmth. Originally from sperm whales, modern ambergris is synthetic (ambroxan). It adds a luminous, skin-like quality and incredible projection to fragrances.", category: "Animalic", origin: "Synthetic (historically from sperm whales)", image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=600&h=400&fit=crop&q=80" },
  "civet": { description: "Animalic, musky, and sensual with a complex, feral quality. Once derived from the civet cat, modern civet notes are synthetic. In small doses, it adds a fascinating depth and sensuality.", category: "Animalic", origin: "Synthetic (historically from civet cat)", image: "https://images.unsplash.com/photo-1541643600914-78b084683601?w=600&h=400&fit=crop&q=80" },
  "castoreum": { description: "Leathery, smoky, and animalic with birch tar and vanilla facets. Originally from beavers, it's now synthetic. Castoreum adds a distinctive, complex leather-like quality to classic and vintage perfumes.", category: "Animalic", origin: "Synthetic (historically from beavers)", image: "https://images.unsplash.com/photo-1473188588951-f4b4b6560e4f?w=600&h=400&fit=crop&q=80" },

  // ── AROMATIC & HERBAL ──
  "lavender": { description: "Aromatic, herbal, and calming. A cornerstone of fougère fragrances and men's perfumery. French lavender from Provence is the most prized, offering a clean, slightly camphorous aroma with a floral sweetness.", category: "Aromatic", origin: "Provence, France", image: "https://images.unsplash.com/photo-1499002238440-d264edd596ec?w=600&h=400&fit=crop&q=80" },
  "tobacco": { description: "Warm, sweet, and slightly honeyed. Tobacco notes evoke dried tobacco leaves, pipe tobacco, or cured Virginia leaf. It adds a cozy, sophisticated warmth that pairs wonderfully with vanilla, spices, and leather.", category: "Aromatic", origin: "Cuba, Virginia, Turkey", image: "https://images.unsplash.com/photo-1527525443983-6e60c75fff46?w=600&h=400&fit=crop&q=80" },
  "patchouli": { description: "Earthy, woody, and slightly sweet with a deep, rich character. Patchouli adds remarkable depth and longevity. Dark patchouli is rich and chocolatey, while light patchouli is cleaner and more transparent.", category: "Aromatic", origin: "Indonesia, Philippines", image: "https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=600&h=400&fit=crop&q=80" },
  "basil": { description: "Aromatic, green, and slightly anise-like with a fresh, herbal vitality. Basil adds an unexpected freshness to fragrances, bridging the gap between herbs and spices. It works beautifully with citrus and green notes.", category: "Aromatic", origin: "Mediterranean, Asia", image: "https://images.unsplash.com/photo-1618164435735-413d3b066c9a?w=600&h=400&fit=crop&q=80" },
  "rosemary": { description: "Herbal, camphorous, and woody with a clean, Mediterranean freshness. Rosemary adds an aromatic, slightly medicinal quality that evokes herb gardens and coastal hillsides.", category: "Aromatic", origin: "Mediterranean", image: "https://images.unsplash.com/photo-1515586838455-8f8045940b5b?w=600&h=400&fit=crop&q=80" },
  "thyme": { description: "Herbal, warm, and slightly medicinal with a dry, green character. Thyme adds an authentic herbal quality to aromatic compositions. It pairs naturally with lavender and other Mediterranean herbs.", category: "Aromatic", origin: "Mediterranean", image: "https://images.unsplash.com/photo-1515586838455-8f8045940b5b?w=600&h=400&fit=crop&q=80" },
  "mint": { description: "Cool, fresh, and invigorating with an icy clarity. Peppermint is sharp and cooling, while spearmint is sweeter and greener. Mint adds instant freshness and an energizing quality to compositions.", category: "Aromatic", origin: "Americas, Europe", image: "https://images.unsplash.com/photo-1628556270448-4d4e4148e1b1?w=600&h=400&fit=crop&q=80" },
  "sage": { description: "Herbal, slightly camphorous, and dry with an aromatic warmth. Clary sage is more floral and has a muscatel, wine-like quality that's prized in perfumery. It adds depth to aromatic and herbal compositions.", category: "Aromatic", origin: "Mediterranean, Europe", image: "https://images.unsplash.com/photo-1515586838455-8f8045940b5b?w=600&h=400&fit=crop&q=80" },
  "tea": { description: "Clean, astringent, and slightly smoky with a refined, calming quality. Green tea is bright and dewy, black tea is richer and malty, while white tea is soft and delicate. Tea notes add a sophisticated minimalism.", category: "Aromatic", origin: "China, Japan, India", image: "https://images.unsplash.com/photo-1556881286-fc6915169721?w=600&h=400&fit=crop&q=80" },
  "green tea": { description: "Bright, clean, and slightly astringent with a dewy, calming quality. Green tea became iconic in perfumery through Elizabeth Arden's Green Tea. It adds a serene, transparent freshness that feels modern and refined.", category: "Aromatic", origin: "China, Japan", image: "https://images.unsplash.com/photo-1556881286-fc6915169721?w=600&h=400&fit=crop&q=80" },

  // ── FRUITS ──
  "peach": { description: "Juicy, sweet, and velvety with a soft, fuzzy warmth. Peach adds a lush, feminine fruitiness that bridges fresh and gourmand. The lactone compounds in peach create a creamy, skin-like quality.", category: "Fruity", origin: "China, Mediterranean", image: "https://images.unsplash.com/photo-1629828874514-4a8e4ef934af?w=600&h=400&fit=crop&q=80" },
  "apple": { description: "Crisp, fresh, and clean with a green or red character depending on the variety. Green apple is tart and sparkling, while red apple is sweeter. Apple adds a youthful, approachable freshness.", category: "Fruity", origin: "Central Asia, worldwide", image: "https://images.unsplash.com/photo-1568702846914-96b305d2aaeb?w=600&h=400&fit=crop&q=80" },
  "pear": { description: "Soft, watery, and clean with a subtle, delicate sweetness. Pear adds a gentle, transparent fruitiness that's less assertive than apple. It creates an airy, feminine quality in fresh compositions.", category: "Fruity", origin: "Europe, Asia", image: "https://images.unsplash.com/photo-1514756331096-242fdeb70d4a?w=600&h=400&fit=crop&q=80" },
  "plum": { description: "Rich, dark, and jammy with a wine-like depth. Plum adds a luxurious, slightly decadent fruitiness that works beautifully in oriental and autumnal compositions. It has a velvety, almost boozy quality.", category: "Fruity", origin: "China, Europe", image: "https://images.unsplash.com/photo-1601493700631-2b16ec4b4716?w=600&h=400&fit=crop&q=80" },
  "fig": { description: "Green, milky, and slightly coconut-like with a woody warmth. Fig in perfumery captures both the fruit and the leaf — the leaf is greener and more aromatic, while the fruit is sweeter and creamier.", category: "Fruity", origin: "Mediterranean", image: "https://images.unsplash.com/photo-1601379329542-31c59347e2b8?w=600&h=400&fit=crop&q=80" },
  "raspberry": { description: "Tart, sweet, and jewel-like with a vibrant berry character. Raspberry adds a sparkling, slightly powdery fruitiness. The ionone compounds give it a subtle violet-like facet.", category: "Fruity", origin: "Europe, Americas", image: "https://images.unsplash.com/photo-1577003811926-53b288a6e5d0?w=600&h=400&fit=crop&q=80" },
  "blackberry": { description: "Dark, juicy, and slightly tart with a wild, hedgerow character. Blackberry adds a rich, deep fruitiness that's less sweet than raspberry. It works beautifully in dark, mysterious compositions.", category: "Fruity", origin: "Europe, Americas", image: "https://images.unsplash.com/photo-1615484477778-ca3b77940c25?w=600&h=400&fit=crop&q=80" },
  "cherry": { description: "Sweet, bright, and slightly almond-like with a juicy, candy-like quality. Cherry can range from tart Morello to sweet Maraschino. It adds a playful, youthful fruitiness often paired with almonds and vanilla.", category: "Fruity", origin: "Europe, Americas, Japan", image: "https://images.unsplash.com/photo-1559181567-c3190ca9959b?w=600&h=400&fit=crop&q=80" },
  "lychee": { description: "Exotic, floral, and rosy with a translucent sweetness. Lychee bridges the gap between fruit and flower, adding a sophisticated, almost peony-like quality. It's popular in modern feminine fragrances.", category: "Fruity", origin: "China, Southeast Asia", image: "https://images.unsplash.com/photo-1577003811926-53b288a6e5d0?w=600&h=400&fit=crop&q=80" },
  "mango": { description: "Tropical, lush, and creamy with a rich, exotic sweetness. Mango adds a sun-drenched, vacation quality to fragrances. It pairs naturally with coconut, vanilla, and tropical flowers.", category: "Fruity", origin: "India, Southeast Asia", image: "https://images.unsplash.com/photo-1553279768-865429fa0078?w=600&h=400&fit=crop&q=80" },
  "pineapple": { description: "Bright, tropical, and juicy with a slightly fermented edge. Pineapple adds a bold, exotic fruitiness. Ethyl maltol and DMHF are key molecules used to create pineapple effects in niche perfumery.", category: "Fruity", origin: "South America, Philippines", image: "https://images.unsplash.com/photo-1550258987-190a2d41a8ba?w=600&h=400&fit=crop&q=80" },
  "pomegranate": { description: "Tart, jewel-like, and slightly tannic with a sophisticated fruitiness. Pomegranate adds a modern, unexpected freshness that works in both fruity and woody compositions.", category: "Fruity", origin: "Iran, Mediterranean", image: "https://images.unsplash.com/photo-1541344999736-83eca272f6fc?w=600&h=400&fit=crop&q=80" },
  "passion fruit": { description: "Exotic, tangy, and tropical with a slightly tart, seductive quality. Passion fruit adds a vibrant, sensual fruitiness. Its unique aroma profile bridges sweet and tart in unexpected ways.", category: "Fruity", origin: "South America", image: "https://images.unsplash.com/photo-1577003811926-53b288a6e5d0?w=600&h=400&fit=crop&q=80" },

  // ── GREEN & AQUATIC ──
  "oakmoss": { description: "Earthy, forest-like, and damp with a rich, green complexity. Oakmoss is one of the most important ingredients in chypre fragrances. IFRA restrictions have limited its use, but it remains a beloved note.", category: "Green", origin: "European forests", image: "https://images.unsplash.com/photo-1418065460487-3e41a6c84dc5?w=600&h=400&fit=crop&q=80" },
  "moss": { description: "Damp, green, and earthy with a forest-floor quality. Moss notes evoke wet woods and shaded glens. Along with oakmoss, tree moss is used in perfumery to add a natural, outdoorsy depth.", category: "Green", origin: "Various forests", image: "https://images.unsplash.com/photo-1418065460487-3e41a6c84dc5?w=600&h=400&fit=crop&q=80" },
  "grass": { description: "Fresh, green, and slightly sweet with a just-cut-lawn quality. Grass notes add a natural, outdoor freshness that's lively and vibrant. It creates an impression of open fields and summer days.", category: "Green", origin: "Synthetic accord", image: "https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=600&h=400&fit=crop&q=80" },
  "seaweed": { description: "Marine, iodine-like, and salty with an oceanic depth. Seaweed notes add a distinctive coastal character that goes beyond generic 'aquatic' accords. It creates a raw, natural marine quality.", category: "Aquatic", origin: "Coastal regions", image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=600&h=400&fit=crop&q=80" },
  "sea salt": { description: "Mineral, crisp, and briny with a skin-like warmth. Sea salt notes add a natural, effortless quality that evokes ocean air and sun-kissed skin. Very popular in modern clean and aquatic fragrances.", category: "Aquatic", origin: "Synthetic accord", image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=600&h=400&fit=crop&q=80" },

  // ── MISCELLANEOUS ──
  "iso e super": { description: "A modern synthetic molecule that creates a smooth, velvety, woody-amber aura. Often described as a 'your skin but better' effect — it has a chameleon-like quality, smelling slightly different on every wearer. The backbone of many modern hits.", category: "Synthetic", origin: "Laboratory", image: "https://images.unsplash.com/photo-1541643600914-78b084683601?w=600&h=400&fit=crop&q=80" },
  "ambroxan": { description: "A powerful synthetic that recreates ambergris — warm, mineral, slightly salty with incredible projection. It creates a luminous, skin-like halo. The molecule behind Dior Sauvage's massive sillage and many modern blockbusters.", category: "Synthetic", origin: "Laboratory", image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=600&h=400&fit=crop&q=80" },
  "cashmeran": { description: "Warm, musky, and woody with a cozy, fabric-like quality. Cashmeran evokes cashmere sweaters and intimate warmth. It adds a soft, enveloping comfort that's become essential in cozy, skin-scent fragrances.", category: "Synthetic", origin: "Laboratory", image: "https://images.unsplash.com/photo-1517263904808-5dc91e3e7044?w=600&h=400&fit=crop&q=80" },

  // ── ADDITIONAL WOODS ──
  "agarwood": { description: "The resinous heartwood of Aquilaria trees — the source of oud. When the tree becomes infected with a specific mold, it produces a dark, fragrant resin prized as one of the most luxurious perfumery materials in the world.", category: "Wood", origin: "Southeast Asia, India" },
  "rosewood": { description: "Soft, rosy, and slightly spicy with a warm woody sweetness. Brazilian rosewood (Aniba rosaeodora) contains linalool, giving it a floral-woody character. Now heavily regulated due to deforestation concerns.", category: "Wood", origin: "Brazil, Amazon" },
  "pine": { description: "Fresh, resinous, and bracing with a clean, forest-air quality. Pine notes evoke cold mountain air and winter landscapes. Commonly used in aromatic and fougère compositions for a natural freshness.", category: "Wood", origin: "Northern forests" },
  "juniper": { description: "Crisp, green, and slightly gin-like with an aromatic, resinous quality. Juniper berries add a distinctive freshness that bridges herbal and woody categories. The signature botanical in gin.", category: "Wood", origin: "Europe, North America" },
  "oudh": { description: "An alternate spelling of oud — the precious dark resin from infected agarwood trees. Oudh is central to Arabian perfumery, adding deep, smoky, animalic complexity that can range from sweet to medicinal.", category: "Wood", origin: "Southeast Asia, Middle East" },
  "wood": { description: "A general woody accord that can encompass various timber notes from dry cedar to creamy sandalwood. Woody notes form the backbone of many fragrance families, adding structure, warmth, and longevity.", category: "Wood", origin: "Various" },

  // ── ADDITIONAL FLORALS ──
  "white flowers": { description: "A lush blend of heady white florals like jasmine, tuberose, gardenia, and orange blossom. White flower accords are intensely feminine, narcotic, and sensual — the olfactory equivalent of a summer night garden.", category: "Floral", origin: "Accord" },
  "honeysuckle": { description: "Sweet, nectarous, and airy with a delicate, natural sweetness. Honeysuckle evokes childhood memories of plucking flowers and tasting nectar. In perfumery, it adds a light, innocent floral sweetness.", category: "Floral", origin: "Europe, Asia" },
  "carnation": { description: "Spicy, clove-like, and powdery with a peppery warmth. Carnation is one of the most distinctive florals — more spicy than sweet. It adds vintage elegance and a sophisticated, slightly masculine floral quality.", category: "Floral", origin: "Mediterranean" },
  "frangipani": { description: "Exotic, creamy, and tropical with a rich, intoxicating sweetness. Also known as plumeria, frangipani evokes Hawaiian leis and tropical gardens. It bridges floral and gourmand with its custard-like richness.", category: "Floral", origin: "Pacific Islands, Caribbean" },
  "lotus": { description: "Aquatic, clean, and ethereally delicate with a watery freshness. Lotus adds a serene, meditative quality to compositions. It's lighter and more transparent than most florals, evoking still ponds and zen gardens.", category: "Floral", origin: "Asia" },
  "mimosa": { description: "Powdery, almond-like, and honeyed with a soft, fuzzy warmth. Mimosa absolute captures both the flower's sweetness and a distinctive green, cucumber-like facet. It's a beloved note in feminine fragrances.", category: "Floral", origin: "France, Morocco" },
  "cherry blossom": { description: "Delicate, airy, and subtly sweet with an almost transparent quality. Cherry blossom (sakura) in perfumery captures the fleeting beauty of spring — light, romantic, and gently powdery.", category: "Floral", origin: "Japan" },
  "poppy": { description: "Light, airy, and slightly green with a delicate, transparent floral character. Poppy in perfumery is more of an impression than a direct extraction — soft, feminine, and dreamily romantic.", category: "Floral", origin: "Various" },
  "daisy": { description: "Fresh, green, and innocently cheerful with a light, dewy quality. Daisy notes add a youthful, carefree freshness. They're popular in young, casual fragrances that evoke spring meadows.", category: "Floral", origin: "Europe" },
  "water lily": { description: "Aquatic, clean, and delicately floral with a transparent, dewy quality. Water lily adds a fresh, serene character that bridges floral and aquatic categories beautifully.", category: "Floral", origin: "Various" },
  "tiare flower": { description: "Rich, creamy, and tropical with a coconut-like sweetness. Tiare (Tahitian gardenia) is the signature flower of the South Pacific, evoking tropical beaches and monoi oil.", category: "Floral", origin: "Tahiti, Pacific Islands" },
  "chamomile": { description: "Herbal, apple-like, and soothing with a gentle, calming quality. Roman chamomile is fruity and fresh, while German chamomile is more herbaceous. Adds a natural, comforting warmth.", category: "Floral", origin: "Europe" },

  // ── ADDITIONAL SPICES ──
  "sichuan pepper": { description: "Tingling, electric, and citrusy with a unique numbing sensation. Sichuan pepper creates a buzzing, almost effervescent quality that's completely different from black or pink pepper. Increasingly popular in niche perfumery.", category: "Spice", origin: "China" },
  "turmeric": { description: "Warm, earthy, and slightly bitter with a golden, spicy character. Turmeric adds an exotic, grounding quality. Its distinctive aroma bridges spicy and woody categories.", category: "Spice", origin: "India, Southeast Asia" },
  "anise": { description: "Sweet, licorice-like, and warm with a distinctive aromatic sweetness. Anise adds a cozy, slightly mysterious quality. Its anethole content creates a sweet, herbal warmth.", category: "Spice", origin: "Mediterranean" },
  "fennel": { description: "Sweet, anise-like, and aromatic with a fresh, slightly herbal quality. Fennel is lighter than anise, adding a subtle sweetness with a green, clean facet.", category: "Spice", origin: "Mediterranean" },
  "juniper berries": { description: "Aromatic, fresh, and gin-like with a piney, slightly sweet quality. Juniper berries are the signature botanical of gin, adding a crisp, outdoorsy freshness to compositions.", category: "Spice", origin: "Europe" },

  // ── ADDITIONAL GOURMAND ──
  "brown sugar": { description: "Rich, warm, and molasses-like with a caramelized depth. Brown sugar is darker and more complex than white sugar notes, adding a cozy, baked-goods warmth.", category: "Gourmand", origin: "Accord" },
  "rum": { description: "Rich, sweet, and boozy with warm molasses and caramel facets. Rum adds a festive, indulgent quality. Rum absolute is used in perfumery for its complex, fermented sweetness.", category: "Gourmand", origin: "Caribbean" },
  "whiskey": { description: "Smoky, warm, and oaky with a refined, boozy depth. Whiskey notes evoke leather armchairs and firelit evenings, adding a sophisticated, masculine warmth.", category: "Gourmand", origin: "Accord" },
  "cocoa": { description: "Rich, warm, and subtly bitter with a dry, powdery chocolate quality. Cocoa absolute captures the raw essence of cacao beans before they become chocolate — earthy, deep, and slightly roasted.", category: "Gourmand", origin: "West Africa, South America" },
  "milk": { description: "Creamy, soft, and comforting with a gentle, lactonic sweetness. Milk notes add an intimate, skin-like quality. They're created using lactone molecules that evoke warm dairy.", category: "Gourmand", origin: "Accord" },
  "sugar": { description: "Sweet, clean, and sparkling. Sugar notes in perfumery can range from crystalline and sharp to warm and caramelized. They add immediate sweetness and approachability.", category: "Gourmand", origin: "Accord" },
  "whipped cream": { description: "Light, airy, and sweetly creamy with a fluffy, indulgent quality. Whipped cream notes add a soft, playful gourmand character that's lighter than vanilla or caramel.", category: "Gourmand", origin: "Accord" },
  "cotton candy": { description: "Airy, sweet, and nostalgic with a spun-sugar lightness. Cotton candy notes evoke carnivals and childhood. Created using ethyl maltol, they add a playful, pink sweetness.", category: "Gourmand", origin: "Synthetic" },
  "pistachio": { description: "Nutty, creamy, and slightly sweet with a distinctive green quality. Pistachio adds a gourmet, sophisticated nuttiness that's become trendy in modern niche perfumery.", category: "Gourmand", origin: "Middle East" },
  "hazelnut": { description: "Warm, nutty, and slightly sweet with a roasted, Nutella-like quality. Hazelnut adds a cozy, indulgent gourmand warmth that pairs beautifully with coffee and chocolate.", category: "Gourmand", origin: "Turkey, Italy" },

  // ── ADDITIONAL FRUITS ──
  "apricot": { description: "Soft, velvety, and sun-warmed with a gentle, stone-fruit sweetness. Apricot is less juicy than peach and more delicate, adding a warm, fuzzy fruitiness.", category: "Fruity", origin: "Central Asia" },
  "banana": { description: "Creamy, tropical, and sweet with a distinctive, instantly recognizable character. Banana in perfumery adds an exotic, playful quality — often found as a facet of ylang ylang.", category: "Fruity", origin: "Southeast Asia" },
  "watermelon": { description: "Fresh, watery, and lightly sweet with a clean, summery quality. Watermelon adds a transparent, playful freshness that's lighter and more aquatic than most fruit notes.", category: "Fruity", origin: "Accord" },
  "strawberry": { description: "Sweet, juicy, and bright with a candy-like freshness. Strawberry adds a youthful, playful fruitiness. In perfumery, it ranges from realistic fresh berry to sweeter, jammy interpretations.", category: "Fruity", origin: "Europe, Americas" },
  "grape": { description: "Juicy, sweet, and slightly musky with a wine-like quality. Grape notes can range from fresh Muscat to fermented, wine-like facets. They add an unexpected, playful fruitiness.", category: "Fruity", origin: "Mediterranean" },
  "blood orange": { description: "Vibrant, tangy, and deeply citrusy with a distinctive red, berry-like sweetness. Blood orange is more complex and exotic than regular orange, adding a dramatic, jewel-toned brightness.", category: "Citrus", origin: "Sicily, Mediterranean" },
  "tangerine": { description: "Bright, sweet, and zesty with a slightly floral, mandarin-like quality. Tangerine is cheerful and energizing, adding a burst of sunny citrus freshness.", category: "Citrus", origin: "Southeast Asia, Mediterranean" },
  "kumquat": { description: "Tart, bright, and aromatic with a unique sweet-and-sour citrus quality. Kumquat adds an unexpected, playful citrus character that's more complex than standard orange.", category: "Citrus", origin: "China, Southeast Asia" },
  "cassis": { description: "Tart, dark, and intensely fruity with a catty, sulfurous edge. Blackcurrant (cassis) bud absolute is one of the most distinctive fruit notes — sharp, green, and deeply characterful.", category: "Fruity", origin: "France, Europe" },
  "rhubarb": { description: "Tart, green, and slightly fruity with a sharp, refreshing quality. Rhubarb adds a modern, unexpected freshness that bridges fruit and green categories.", category: "Fruity", origin: "Europe, Asia" },

  // ── ADDITIONAL GREEN & FRESH ──
  "green leaves": { description: "Fresh, crisp, and vegetal with a just-picked, natural quality. Green leaf notes capture the essence of crushed foliage — bright, clean, and alive with natural energy.", category: "Green", origin: "Accord" },
  "ivy": { description: "Green, cool, and slightly woody with a damp, shaded quality. Ivy notes evoke old stone walls and secret gardens, adding an English garden atmosphere.", category: "Green", origin: "Europe" },
  "bamboo leaf": { description: "Clean, green, and subtly woody with a fresh, transparent quality. Bamboo leaf adds a zen-like calm and minimalist freshness to compositions.", category: "Green", origin: "Asia" },
  "eucalyptus": { description: "Cool, camphorous, and invigorating with a clean, medicinal freshness. Eucalyptus adds an energizing, spa-like quality. It's sharper and more mentholated than most aromatic herbs.", category: "Aromatic", origin: "Australia" },
  "watercress": { description: "Peppery, green, and slightly aquatic with a fresh, crisp quality. Watercress notes add a unique, slightly biting freshness that's more complex than simple green notes.", category: "Green", origin: "Europe" },

  // ── ADDITIONAL AQUATIC & MARINE ──
  "ocean": { description: "Fresh, ozonic, and mineral with a vast, open-water quality. Ocean accords evoke crashing waves and sea spray, created using synthetic molecules like calone.", category: "Aquatic", origin: "Synthetic accord" },
  "rain": { description: "Fresh, mineral, and petrichor-like with a clean, earthy quality. Rain accords capture the scent of wet earth and ozone after a storm — a modern, evocative note.", category: "Aquatic", origin: "Synthetic accord" },
  "water": { description: "Clean, transparent, and mineral with a pure, refreshing quality. Water notes add a sheer, crystalline freshness to compositions without adding sweetness or heaviness.", category: "Aquatic", origin: "Synthetic accord" },

  // ── ADDITIONAL AROMATIC ──
  "cannabis": { description: "Green, herbal, and slightly skunky with earthy, woody undertones. Cannabis notes in perfumery are extracted from hemp seeds and add an edgy, modern herbaceousness.", category: "Aromatic", origin: "Various" },
  "hay": { description: "Warm, sweet, and slightly coumarinic with a sun-dried, golden quality. Hay notes evoke summer fields and contain natural coumarin. They add a rustic, pastoral warmth.", category: "Aromatic", origin: "Various" },
  "oregano": { description: "Warm, herbal, and slightly camphorous with a Mediterranean, kitchen-herb quality. Oregano adds an aromatic, rustic warmth that's distinctive and slightly savory.", category: "Aromatic", origin: "Mediterranean" },
  "tarragon": { description: "Anise-like, herbal, and slightly sweet with a sophisticated, culinary quality. Tarragon adds an unexpected, refined herbal note that bridges sweet and savory.", category: "Aromatic", origin: "Europe, Western Asia" },
  "dill": { description: "Fresh, green, and slightly anise-like with a distinctive herbal character. Dill adds an unusual, refreshing quality that's sometimes found in niche compositions.", category: "Aromatic", origin: "Mediterranean, Europe" },

  // ── ADDITIONAL RESINS ──
  "opoponax": { description: "Sweet, balsamic, and warm with a honeyed, myrrh-like quality. Opoponax (sweet myrrh) is softer and more approachable than true myrrh, adding a gentle, resinous sweetness.", category: "Resin", origin: "Somalia, Ethiopia" },
  "copal": { description: "Fresh, citrusy, and resinous with a bright, clean quality. Copal is younger than amber and has a lighter, more translucent character. Used traditionally as incense in Mesoamerica.", category: "Resin", origin: "Central America" },
  "beeswax": { description: "Warm, honeyed, and waxy with a golden, comforting richness. Beeswax absolute adds a natural, cozy sweetness that bridges gourmand and animalic categories beautifully.", category: "Resin", origin: "Various" },

  // ── ADDITIONAL MUSKS & SKIN ──
  "skin": { description: "Warm, intimate, and subtly musky with a personal, lived-in quality. Skin accords aim to replicate the natural scent of clean, warm skin — the ultimate 'your-skin-but-better' effect.", category: "Animalic", origin: "Synthetic accord" },
  "cashmere": { description: "Soft, warm, and enveloping with a fabric-like coziness. Cashmere notes in perfumery create the olfactory impression of luxury knitwear — intimate, comforting, and quietly luxurious.", category: "Animalic", origin: "Synthetic accord" },
  "clean musk": { description: "Fresh, soapy, and skin-like with a just-showered quality. Clean musk notes are the foundation of modern 'clean' perfumery — intimate, approachable, and universally appealing.", category: "Animalic", origin: "Synthetic" },

  // ── ADDITIONAL MISCELLANEOUS ──
  "metallic notes": { description: "Sharp, cold, and mineral with an industrial, modern quality. Metallic notes add an edgy, contemporary character. They can evoke anything from cold steel to warm copper.", category: "Synthetic", origin: "Accord" },
  "smoke": { description: "Dark, warm, and atmospheric with a campfire or hearth quality. Smoke notes add drama and depth, evoking cozy fireplaces, incense ceremonies, or smoldering wood.", category: "Aromatic", origin: "Accord" },
  "dust": { description: "Dry, powdery, and atmospheric with a nostalgic, attic-like quality. Dust notes evoke old books, sun-warmed rooms, and vintage memories. A niche favorite for its evocative character.", category: "Aromatic", origin: "Accord" },
  "petitgrain": { description: "Fresh, green, and woody-citrus with a slightly bitter, aromatic quality. Distilled from bitter orange leaves and twigs, petitgrain is more complex than neroli — greener, drier, and more angular.", category: "Citrus", origin: "Paraguay, France" },
  "linalool": { description: "Floral, fresh, and slightly lavender-like with a clean, calming quality. Linalool is one of the most important aroma molecules — found naturally in lavender, rosewood, and bergamot.", category: "Synthetic", origin: "Natural compound" },
  "hedione": { description: "Fresh, radiant, and jasmine-like with a transparent, airy quality. Hedione revolutionized perfumery when introduced in Eau Sauvage (1966). It adds luminous diffusion and a sense of space.", category: "Synthetic", origin: "Laboratory" },
  "orris": { description: "Powdery, violet-like, and supremely elegant. Orris root (from aged iris rhizomes) is one of perfumery's most expensive materials, requiring 5-7 years of drying. It adds unparalleled refinement.", category: "Floral", origin: "Italy (Tuscany)" },
  "oakwood": { description: "Rich, tannic, and slightly smoky with a wine-barrel warmth. Oak adds a robust, aged quality that evokes whiskey casks and old-growth forests.", category: "Wood", origin: "Europe, North America" },
  "sugi": { description: "Clean, hinoki-like, and aromatic with a distinctly Japanese woodiness. Japanese cedar (sugi) adds a refined, minimalist woody quality that feels both ancient and modern.", category: "Wood", origin: "Japan" },
  "white tea": { description: "Delicate, clean, and subtly sweet with the lightest, most refined tea quality. White tea notes add a quiet sophistication — less astringent than green tea, more ethereal and transparent.", category: "Aromatic", origin: "China" },
  "black tea": { description: "Rich, malty, and slightly smoky with a warm, tannic quality. Black tea adds a refined, British-inflected warmth. Lapsang souchong varieties bring additional smokiness.", category: "Aromatic", origin: "India, China, Sri Lanka" },
  "mate": { description: "Green, herbaceous, and slightly smoky with a South American character. Yerba mate adds an energizing, natural freshness with earthy undertones.", category: "Aromatic", origin: "South America" },
  "immortelle": { description: "Warm, curry-like, and honeyed with a distinctive maple-syrup sweetness. Immortelle (Helichrysum) is unique in perfumery — its warm, hay-like aroma adds an addictive, golden quality.", category: "Aromatic", origin: "Mediterranean, Corsica" },
  "anis": { description: "Sweet, licorice-like, and warmly aromatic. An alternate spelling of anise, this note adds a distinctive herbal sweetness to compositions, particularly in oriental and spicy fragrances.", category: "Spice", origin: "Mediterranean" },
  "davana": { description: "Fruity, warm, and slightly boozy with an apricot-like richness. Davana is unique because its scent changes based on skin chemistry, making every wearer's experience different.", category: "Aromatic", origin: "India" },
  "nagarmotha": { description: "Earthy, woody, and smoky with a vetiver-like depth. Also known as cypriol, nagarmotha is a root from India that adds a deep, grounding earthiness to oriental compositions.", category: "Wood", origin: "India" },
  "aoud": { description: "An alternate transliteration of oud/oudh. This precious resinous wood is the heart of Arabic perfumery, offering smoky, animalic, and deeply rich woody complexity.", category: "Wood", origin: "Southeast Asia, Middle East" },
  "praline rose": { description: "A decadent fusion of caramelized sugar and fresh rose — simultaneously gourmand and floral. This accord creates a romantic, indulgent quality popular in modern feminine perfumery.", category: "Gourmand", origin: "Accord" },
  "amberwood": { description: "A warm blend of amber resin and smooth wood — creating a golden, enveloping base. Amberwood accords add cozy depth and excellent longevity to compositions.", category: "Wood", origin: "Accord" },
  "mastic": { description: "Resinous, aromatic, and slightly piney with a clean, balsamic quality. Mastic gum from the Greek island of Chios has been prized for millennia, adding a distinctive Mediterranean character.", category: "Resin", origin: "Greece (Chios)" },
  "lichen": { description: "Green, earthy, and slightly marine with a damp, forest-like quality. Lichen notes bridge oakmoss and green categories, adding a natural, wild character.", category: "Green", origin: "Various forests" },
};

export default NOTE_ENCYCLOPEDIA;
