/* ═══════════════════════════════════════════════════════════════
   THE DRY DOWN — Fragrance Note Encyclopedia
   100+ notes with descriptions, categories, origins & images
   ═══════════════════════════════════════════════════════════════ */

const NOTE_ENCYCLOPEDIA = {
  // ── WOODS ──
  "oud": { description: "Also known as agarwood, oud is formed when Aquilaria trees become infected with mold. The resulting resin creates one of the most prized and expensive raw materials in perfumery — smoky, animalic, and deeply complex. It's the backbone of Middle Eastern perfumery and has become a global luxury staple.", category: "Wood", origin: "Southeast Asia, Middle East", image: "https://images.unsplash.com/photo-1600857544200-b2f666a9a2ec?w=600&q=80" },
  "sandalwood": { description: "Creamy, warm, and milky — sandalwood is one of the most versatile base notes. Mysore sandalwood from India is considered the finest, offering a rich, buttery aroma. Australian sandalwood is now more commonly used due to sustainability concerns. It blends beautifully with nearly everything.", category: "Wood", origin: "India, Australia", image: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=600&q=80" },
  "cedar": { description: "Clean, dry, and pencil-shaving woody. Virginia cedar is sharp and dry, while Atlas cedar is warmer and more aromatic. Cedar is a foundational woody note that adds structure and a natural crispness to fragrances without being overpowering.", category: "Wood", origin: "North America, Morocco", image: "https://images.unsplash.com/photo-1542273917363-3b1817f69a2d?w=600&q=80" },
  "cedarwood": { description: "A broader term encompassing various cedar species used in perfumery. Cedarwood essential oil provides a warm, balsamic woodiness that forms the backbone of many masculine and unisex compositions. It adds longevity and a natural elegance.", category: "Wood", origin: "North America, Morocco, Virginia", image: "https://images.unsplash.com/photo-1542273917363-3b1817f69a2d?w=600&q=80" },
  "vetiver": { description: "Earthy, smoky, and green with a grounding quality. Haitian vetiver is smoky and deep, while Javanese vetiver is cleaner. Distilled from the roots of a tropical grass, it adds sophistication and depth. Often called 'the oil of tranquility.'", category: "Wood", origin: "Haiti, Java, India", image: "https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=600&q=80" },
  "guaiac wood": { description: "Smoky, creamy, and slightly sweet with tea-like nuances. Guaiac wood (also spelled gaiac) comes from the Palo Santo tree family and adds a distinctive smoky-woody character that bridges the gap between incense and clean woods.", category: "Wood", origin: "South America", image: "https://images.unsplash.com/photo-1473448912268-2022ce9509d8?w=600&q=80" },
  "birch": { description: "Smoky, leathery, and tarry. Birch tar was historically used to create leather accords in perfumery. It gives fragrances a rugged, outdoorsy character with a campfire-like smokiness. Key ingredient in classic Russian Leather compositions.", category: "Wood", origin: "Northern Europe, Russia", image: "https://images.unsplash.com/photo-1588392382834-a891154bca4d?w=600&q=80" },
  "cypress": { description: "Fresh, clean, and slightly resinous with a green, coniferous character. Cypress adds a Mediterranean freshness to compositions, evoking windswept coastal landscapes. It sits beautifully between aromatic herbs and woods.", category: "Wood", origin: "Mediterranean, Southern Europe", image: "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=600&q=80" },
  "driftwood": { description: "A modern perfumery concept that evokes sun-bleached, salt-washed wood. Driftwood accords combine woody, marine, and mineral facets to create a sense of weathered coastal landscapes and ocean-kissed timber.", category: "Wood", origin: "Synthetic accord", image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=600&q=80" },
  "bamboo": { description: "Clean, green, and airy with a fresh woody character. Bamboo in perfumery creates a light, transparent woodiness that feels modern and minimalist. It adds a zen-like calm and fresh green quality.", category: "Wood", origin: "Asia", image: "https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=600&q=80" },
  "teak": { description: "Rich, warm, and slightly honeyed with a luxurious woody character. Teak evokes fine furniture and exotic interiors. In perfumery, it adds a sophisticated warmth that feels both natural and refined.", category: "Wood", origin: "Southeast Asia", image: "https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=600&q=80" },
  "ebony": { description: "Dark, dense, and deeply woody with a smooth, polished quality. Ebony in perfumery creates an impression of dark, precious wood — sophisticated and mysterious with an almost lacquered finish.", category: "Wood", origin: "Tropical regions", image: "https://images.unsplash.com/photo-1473448912268-2022ce9509d8?w=600&q=80" },

  // ── FLORALS ──
  "rose": { description: "The queen of flowers in perfumery. Different varieties — Turkish, Bulgarian, Damascene, Taifi, Centifolia — each bring distinct facets from honeyed and jammy to fresh and dewy. Rose is endlessly versatile, appearing in everything from fresh colognes to deep orientals.", category: "Floral", origin: "Turkey, Bulgaria, Morocco, Saudi Arabia", image: "https://images.unsplash.com/photo-1490750967868-88aa4f44baee?w=600&q=80" },
  "jasmine": { description: "Rich, intoxicating, and narcotic. Jasmine is one of the most important floral notes in perfumery, adding sensuality and depth. Jasmine Sambac is sweeter and more tropical, while Jasmine Grandiflorum is more classical and heady.", category: "Floral", origin: "India, Egypt, Morocco", image: "https://images.unsplash.com/photo-1587727005224-82e3d9e0b3a6?w=600&q=80" },
  "iris": { description: "Powdery, elegant, and expensive. Iris (orris root) is one of the most costly perfume ingredients, requiring up to seven years of aging. It adds a sophisticated, lipstick-like powdery quality that's unmistakable in high-end perfumery.", category: "Floral", origin: "Italy, Morocco", image: "https://images.unsplash.com/photo-1585386959984-a4155224a1ad?w=600&q=80" },
  "tuberose": { description: "Intensely heady, creamy, and narcotic. Tuberose is one of the most powerful white florals, adding a rich, almost buttery quality. It's both beautiful and animalic — a flower that demands attention and dominates any composition.", category: "Floral", origin: "India, Morocco", image: "https://images.unsplash.com/photo-1490750967868-88aa4f44baee?w=600&q=80" },
  "lily": { description: "Clean, fresh, and dewy with a waxy sweetness. Lily of the valley (muguet) is one of the most popular floral notes in perfumery. Since it can't be naturally extracted, it's always recreated synthetically, adding a bright, spring-like freshness.", category: "Floral", origin: "Synthetic recreation", image: "https://images.unsplash.com/photo-1490750967868-88aa4f44baee?w=600&q=80" },
  "lily of the valley": { description: "A bright, green, dewy floral that captures the essence of spring. One of the few flowers whose scent cannot be extracted naturally, so perfumers recreate it synthetically. It adds an innocent, fresh, clean quality to compositions.", category: "Floral", origin: "Synthetic recreation", image: "https://images.unsplash.com/photo-1490750967868-88aa4f44baee?w=600&q=80" },
  "orange blossom": { description: "Sweet, honeyed, and narcotic with a waxy green facet. Orange blossom (neroli from the flowers, petit grain from the leaves) is one of the most beloved florals. It's the heart of many classic colognes and oriental fragrances.", category: "Floral", origin: "Morocco, Tunisia, South of France", image: "https://images.unsplash.com/photo-1557800636-894a64c1696f?w=600&q=80" },
  "magnolia": { description: "Lush, creamy, and lemony with a champagne-like effervescence. Magnolia adds a bright, sophisticated floral quality that feels both fresh and luxurious. It's less heavy than jasmine but more complex than simple white florals.", category: "Floral", origin: "China, Americas", image: "https://images.unsplash.com/photo-1490750967868-88aa4f44baee?w=600&q=80" },
  "ylang ylang": { description: "Rich, exotic, and intensely sweet with banana-like and custard facets. Ylang ylang is a tropical flower used extensively in oriental and floral perfumes. Different distillation grades (Extra, I, II, III) offer varying intensities.", category: "Floral", origin: "Comoros Islands, Madagascar", image: "https://images.unsplash.com/photo-1490750967868-88aa4f44baee?w=600&q=80" },
  "peony": { description: "Soft, fresh, and rosy with a hint of green and watermelon. Peony adds a delicate, feminine floral quality that's lighter than rose but more complex than simple clean florals. Popular in modern, youthful fragrances.", category: "Floral", origin: "China, Europe", image: "https://images.unsplash.com/photo-1490750967868-88aa4f44baee?w=600&q=80" },
  "orchid": { description: "Exotic, powdery, and creamy with a velvety richness. Orchid notes in perfumery are typically synthetic recreations that evoke luxury and sensuality. They add a refined, sophisticated floral quality.", category: "Floral", origin: "Synthetic accord", image: "https://images.unsplash.com/photo-1567696911980-2eed69a46042?w=600&q=80" },
  "violet": { description: "Powdery, sweet, and slightly green. Violet has a unique ability to 'disappear' from your perception due to ionone compounds. Violet leaf is greener and crisper, while violet flower is sweeter and more powdery.", category: "Floral", origin: "Egypt, France", image: "https://images.unsplash.com/photo-1490750967868-88aa4f44baee?w=600&q=80" },
  "gardenia": { description: "Lush, creamy, and tropical with a buttery richness. Gardenia is one of the most beautiful white florals — heady and intoxicating without being as heavy as tuberose. It adds a luxurious, velvety quality.", category: "Floral", origin: "China, Japan", image: "https://images.unsplash.com/photo-1490750967868-88aa4f44baee?w=600&q=80" },
  "freesia": { description: "Light, peppery, and fresh with a clean, zesty character. Freesia adds brightness and a subtle spicy-floral accent to compositions. It's a popular heart note in fresh and clean fragrances.", category: "Floral", origin: "South Africa", image: "https://images.unsplash.com/photo-1490750967868-88aa4f44baee?w=600&q=80" },
  "geranium": { description: "Green, rosy, and slightly minty with a citrusy brightness. Geranium is a versatile note that bridges floral and aromatic categories. Egyptian geranium is considered the finest quality, adding natural elegance.", category: "Floral", origin: "Egypt, Réunion", image: "https://images.unsplash.com/photo-1490750967868-88aa4f44baee?w=600&q=80" },
  "plumeria": { description: "Exotic, creamy, and tropical with hints of jasmine and citrus. Also known as frangipani, this Hawaiian flower adds a lush, tropical floral quality that evokes island paradise and warm ocean breezes.", category: "Floral", origin: "Pacific Islands, Caribbean", image: "https://images.unsplash.com/photo-1490750967868-88aa4f44baee?w=600&q=80" },
  "heliotrope": { description: "Powdery, almond-like, and vanillic with a cherry-pie sweetness. Heliotrope bridges the floral and gourmand worlds, adding a soft, comforting quality that's both elegant and cozy.", category: "Floral", origin: "Peru, Mediterranean", image: "https://images.unsplash.com/photo-1490750967868-88aa4f44baee?w=600&q=80" },
  "neroli": { description: "Fresh, sparkling, and green-floral with a honeyed depth. Distilled from bitter orange blossoms, neroli is one of the finest citrus-floral ingredients. It's the heart of classic Eau de Cologne and adds sophisticated freshness.", category: "Floral", origin: "Tunisia, Morocco, Egypt", image: "https://images.unsplash.com/photo-1557800636-894a64c1696f?w=600&q=80" },

  // ── CITRUS ──
  "bergamot": { description: "A citrus fruit that provides the bright, slightly bitter, aromatic opening found in many fragrances. It's the backbone of Earl Grey tea's distinctive flavor and the cornerstone ingredient of classic Eau de Cologne.", category: "Citrus", origin: "Calabria, Italy", image: "https://images.unsplash.com/photo-1611080626919-7cf5a9dbab5b?w=600&q=80" },
  "lemon": { description: "Bright, zesty, and immediately uplifting. Lemon is one of the most universally recognized citrus notes, adding a clean, sparkling freshness to openings. Sicilian lemon is the most prized variety in perfumery.", category: "Citrus", origin: "Sicily, Italy", image: "https://images.unsplash.com/photo-1590502593747-42a996133562?w=600&q=80" },
  "mandarin orange": { description: "Sweet, juicy, and bright with a slightly tangy, rounded character. Mandarin is softer and sweeter than other citrus notes, making it perfect for adding a gentle, approachable freshness to fragrances.", category: "Citrus", origin: "Southern Europe, Brazil", image: "https://images.unsplash.com/photo-1547514701-42fee21e7a3e?w=600&q=80" },
  "grapefruit": { description: "Tart, sparkling, and slightly bitter with a pink, juicy quality. Grapefruit adds an energetic, modern freshness. The nootkatone compound gives it a distinctive character that lasts longer than most citrus notes.", category: "Citrus", origin: "Caribbean, Americas", image: "https://images.unsplash.com/photo-1577234286642-fc512a5f8f11?w=600&q=80" },
  "lime": { description: "Sharp, green, and effervescent with a cocktail-like brightness. Lime adds an upbeat, slightly tropical freshness. Both Persian lime and kaffir lime are used, each offering different facets from zesty to aromatic.", category: "Citrus", origin: "Southeast Asia, Mexico", image: "https://images.unsplash.com/photo-1590502593747-42a996133562?w=600&q=80" },
  "orange": { description: "Sweet, juicy, and sunny. Sweet orange adds a warm, rounded citrus character that's less sharp than lemon and less bitter than bergamot. It's inviting and universally appealing, often used in fresh and gourmand compositions.", category: "Citrus", origin: "Mediterranean, Brazil", image: "https://images.unsplash.com/photo-1547514701-42fee21e7a3e?w=600&q=80" },
  "yuzu": { description: "Tart, green, and aromatic with a distinctive Japanese character. Yuzu is more complex than other citrus notes — slightly floral, herbaceous, and with an almost grapefruit-like bitterness. A favorite in niche perfumery.", category: "Citrus", origin: "Japan, Korea", image: "https://images.unsplash.com/photo-1590502593747-42a996133562?w=600&q=80" },
  "bitter orange": { description: "More complex than sweet orange with a dry, aromatic, slightly medicinal quality. Bitter orange peel is used to create bigarade oil, a classic perfumery ingredient that adds sophistication and depth to citrus accords.", category: "Citrus", origin: "Mediterranean, North Africa", image: "https://images.unsplash.com/photo-1547514701-42fee21e7a3e?w=600&q=80" },

  // ── SPICES ──
  "saffron": { description: "One of the most expensive spices in the world, saffron adds a warm, honeyed, leathery quality to fragrances. It's a signature note in many Middle Eastern perfumes and adds instant richness, exoticism, and depth.", category: "Spice", origin: "Iran, Kashmir", image: "https://images.unsplash.com/photo-1611080626919-7cf5a9dbab5b?w=600&q=80" },
  "pink pepper": { description: "Bright, spicy, and slightly fruity with a rosy sparkle. Not actually related to black pepper — it comes from the Schinus molle tree. Pink pepper adds a modern, lively sparkle to openings that's become a signature of contemporary niche perfumery.", category: "Spice", origin: "South America", image: "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=600&q=80" },
  "black pepper": { description: "Sharp, warm, and biting with a dry, woody-spicy character. Black pepper adds energy and a masculine edge to compositions. It creates a tingling, almost effervescent sensation in fragrance openings.", category: "Spice", origin: "India, Vietnam", image: "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=600&q=80" },
  "pepper": { description: "Warm, sharp, and energetic. Pepper in perfumery can refer to black, white, pink, or Sichuan varieties, each contributing different facets from dry heat to fruity sparkle. It adds life and vibrancy to compositions.", category: "Spice", origin: "India, Southeast Asia", image: "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=600&q=80" },
  "cardamom": { description: "Aromatic, warm, and slightly eucalyptus-like with a fresh, green spiciness. Cardamom is the bridge between fresh and spicy, adding an exotic warmth that's never heavy. A key ingredient in many modern masculine fragrances.", category: "Spice", origin: "Guatemala, India", image: "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=600&q=80" },
  "cinnamon": { description: "Warm, sweet, and spicy with a cozy, festive quality. Cinnamon bark oil is more complex and less sweet than cassia. In perfumery, it adds a comforting warmth that pairs beautifully with vanilla, amber, and florals.", category: "Spice", origin: "Sri Lanka, Indonesia", image: "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=600&q=80" },
  "ginger": { description: "Fresh, zesty, and warm with a citrusy bite. Ginger adds an energetic, slightly lemony spiciness that bridges citrus and spice categories. It's invigorating and adds movement to compositions.", category: "Spice", origin: "Southeast Asia, Jamaica", image: "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=600&q=80" },
  "nutmeg": { description: "Warm, sweet, and slightly narcotic with a cozy, balsamic quality. Nutmeg adds a sophisticated spiciness that's more refined than cinnamon. It's often used in small doses to add depth and warmth.", category: "Spice", origin: "Indonesia, Grenada", image: "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=600&q=80" },
  "clove": { description: "Warm, spicy, and slightly medicinal with an intense, rich character. Eugenol, clove's main component, adds a powerful warm spiciness. It's used carefully in perfumery to add depth without overwhelming.", category: "Spice", origin: "Indonesia, Madagascar", image: "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=600&q=80" },
  "star anise": { description: "Sweet, licorice-like, and aromatic with a warm, comforting quality. Star anise adds an exotic, slightly mysterious spiciness. Its anethole content gives it a distinctive sweetness that works in both oriental and fresh compositions.", category: "Spice", origin: "China, Vietnam", image: "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=600&q=80" },
  "cumin": { description: "Warm, earthy, and slightly animalic with a musky, skin-like quality. Cumin is used very carefully in perfumery — in small doses it adds an intriguing, sensual warmth that mimics body heat. Too much becomes overpowering.", category: "Spice", origin: "Middle East, India", image: "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=600&q=80" },

  // ── GOURMAND ──
  "vanilla": { description: "Derived from the vanilla orchid, this warm, sweet, creamy note is one of the most universally loved in perfumery. It adds comfort, sweetness, and sensuality. Madagascar Bourbon vanilla is considered the finest quality.", category: "Gourmand", origin: "Madagascar, Tahiti, Mexico", image: "https://images.unsplash.com/photo-1631206753348-db44968fd440?w=600&q=80" },
  "tonka bean": { description: "Sweet, warm, and almond-like with hints of vanilla and caramel. Tonka bean contains coumarin, which gives it a distinctive warm, hay-like sweetness. It's become a modern perfumery staple, adding depth without being as sweet as vanilla.", category: "Gourmand", origin: "Venezuela, Brazil", image: "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=600&q=80" },
  "coffee": { description: "Rich, roasted, and slightly bitter. Coffee adds a gourmand warmth and modern edge to fragrances, pairing beautifully with vanilla, leather, and spices. It creates an addictive, energizing quality.", category: "Gourmand", origin: "Ethiopia, Colombia, Brazil", image: "https://images.unsplash.com/photo-1447933601403-0c6688de566e?w=600&q=80" },
  "chocolate": { description: "Rich, bitter-sweet, and indulgent. Chocolate notes in perfumery range from dark and bitter cocoa to sweet milk chocolate. They add a decadent, cozy warmth that's irresistibly comforting.", category: "Gourmand", origin: "Central America, West Africa", image: "https://images.unsplash.com/photo-1481391319762-47dff72954d9?w=600&q=80" },
  "caramel": { description: "Buttery, sweet, and golden with a toffee-like warmth. Caramel adds a luscious gourmand quality that evokes burnt sugar and candy. It's often used alongside vanilla and tonka to create rich, cozy base accords.", category: "Gourmand", origin: "Synthetic accord", image: "https://images.unsplash.com/photo-1631206753348-db44968fd440?w=600&q=80" },
  "honey": { description: "Golden, warm, and animalic with a waxy, sweet richness. Natural honey absolute has a complex, slightly dirty sweetness. In perfumery, it bridges gourmand and animalic categories, adding a primal warmth.", category: "Gourmand", origin: "Various", image: "https://images.unsplash.com/photo-1587049352846-4a222e784d38?w=600&q=80" },
  "coconut": { description: "Tropical, creamy, and sweet with a sunscreen-like warmth. Coconut adds a beachy, vacation quality to fragrances. It pairs beautifully with vanilla, tiare flower, and woody notes for tropical compositions.", category: "Gourmand", origin: "Tropical regions", image: "https://images.unsplash.com/photo-1550317138-10000687a72b?w=600&q=80" },
  "almond": { description: "Nutty, sweet, and slightly bitter with a marzipan-like quality. Bitter almond adds a sophisticated sweetness, while sweet almond is creamier. The benzaldehyde compound gives it a distinctive cherry-like facet.", category: "Gourmand", origin: "Mediterranean, Middle East", image: "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=600&q=80" },
  "praline": { description: "Caramelized, nutty, and rich with a candy-shop sweetness. Praline notes add a sophisticated gourmand quality that's less simple than plain vanilla or sugar. It evokes indulgence and warmth.", category: "Gourmand", origin: "Synthetic accord", image: "https://images.unsplash.com/photo-1631206753348-db44968fd440?w=600&q=80" },
  "marshmallow": { description: "Soft, pillowy, and sugary with an airy, fluffy sweetness. Marshmallow adds a comforting, cloud-like quality to fragrances. It's lighter than vanilla and creates a cozy, skin-scent effect.", category: "Gourmand", origin: "Synthetic accord", image: "https://images.unsplash.com/photo-1631206753348-db44968fd440?w=600&q=80" },
  "toffee": { description: "Rich, buttery, and deeply sweet with a caramelized warmth. Toffee adds a sophisticated, candy-like quality that's darker and more complex than simple sugar notes.", category: "Gourmand", origin: "Synthetic accord", image: "https://images.unsplash.com/photo-1631206753348-db44968fd440?w=600&q=80" },

  // ── RESINS & BALSAMS ──
  "amber": { description: "Not a single ingredient but a blend typically made from labdanum, benzoin, and vanilla. Amber adds warmth, sweetness, and a golden, resinous quality to the base of a fragrance. It's the cornerstone of the oriental fragrance family.", category: "Resin", origin: "Blend of natural resins", image: "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=600&q=80" },
  "incense": { description: "Smoky, sacred, and meditative. Incense notes evoke temples and ceremony, adding a mystical, resinous quality. Olibanum (frankincense) is the most classic incense material, though myrrh and copal are also used.", category: "Resin", origin: "Oman, Somalia, Ethiopia", image: "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=600&q=80" },
  "frankincense": { description: "Sacred, citrusy, and resinous with a clean, almost lemony facet. Frankincense (olibanum) is one of the oldest perfume materials, used for thousands of years. Omani frankincense is considered the finest grade.", category: "Resin", origin: "Oman, Somalia", image: "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=600&q=80" },
  "myrrh": { description: "Warm, balsamic, and slightly medicinal with a dry, resinous depth. Myrrh has been treasured since ancient Egypt and adds a dark, mysterious quality. It's more somber and earthy than frankincense.", category: "Resin", origin: "Somalia, Ethiopia, Yemen", image: "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=600&q=80" },
  "benzoin": { description: "Sweet, warm, and vanilla-like with a balsamic, slightly powdery quality. Benzoin resin adds a soft, cozy sweetness to base accords. Siam benzoin is sweeter, while Sumatra benzoin is more spicy and earthy.", category: "Resin", origin: "Laos, Thailand, Indonesia", image: "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=600&q=80" },
  "labdanum": { description: "Dark, animalic, and amber-like with a leathery, honeyed richness. Harvested from rockrose bushes, labdanum is the primary ingredient in amber accords. It adds a deep, warm, almost animal-like sweetness.", category: "Resin", origin: "Mediterranean", image: "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=600&q=80" },
  "olibanum": { description: "The resin of frankincense — clean, lemony, and resinous with a sacred, meditative quality. Olibanum adds both transparency and depth simultaneously, making it a uniquely versatile ingredient.", category: "Resin", origin: "Oman, Somalia", image: "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=600&q=80" },
  "elemi": { description: "Fresh, citrusy, and resinous with a peppery, slightly dill-like quality. Elemi adds a bright, lively facet to resinous and incense compositions, preventing them from becoming too dark.", category: "Resin", origin: "Philippines", image: "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=600&q=80" },

  // ── MUSKS & ANIMALICS ──
  "musk": { description: "Originally from the musk deer, modern musks are synthetic and come in many varieties — white musk (clean, soapy), skin musk (warm, intimate), and animalic musk (sensual, deep). Musk is the invisible foundation of most perfumes.", category: "Animalic", origin: "Synthetic (historically from musk deer)", image: "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=600&q=80" },
  "white musk": { description: "Clean, soapy, and soft with a laundry-fresh quality. White musk is a family of synthetic musks that create a clean, cozy skin scent. It's the backbone of many 'clean' and 'fresh' fragrances.", category: "Animalic", origin: "Synthetic", image: "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=600&q=80" },
  "leather": { description: "Smoky, animalic, and luxurious. Leather notes in perfumery range from clean suede to dark, tarry birch tar. Leather accords add sophistication, sensuality, and a sense of luxury. Key in fougère and chypre families.", category: "Animalic", origin: "Synthetic accords, birch tar", image: "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=600&q=80" },
  "suede": { description: "Soft, powdery, and velvety with a gentle, tactile warmth. Suede is a lighter, more feminine take on leather — it evokes soft textures and quiet luxury rather than rugged masculinity.", category: "Animalic", origin: "Synthetic accord", image: "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=600&q=80" },
  "ambergris": { description: "Marine, salty, and sweet with a unique oceanic warmth. Originally from sperm whales, modern ambergris is synthetic (ambroxan). It adds a luminous, skin-like quality and incredible projection to fragrances.", category: "Animalic", origin: "Synthetic (historically from sperm whales)", image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=600&q=80" },
  "civet": { description: "Animalic, musky, and sensual with a complex, feral quality. Once derived from the civet cat, modern civet notes are synthetic. In small doses, it adds a fascinating depth and sensuality.", category: "Animalic", origin: "Synthetic (historically from civet cat)", image: "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=600&q=80" },
  "castoreum": { description: "Leathery, smoky, and animalic with birch tar and vanilla facets. Originally from beavers, it's now synthetic. Castoreum adds a distinctive, complex leather-like quality to classic and vintage perfumes.", category: "Animalic", origin: "Synthetic (historically from beavers)", image: "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=600&q=80" },

  // ── AROMATIC & HERBAL ──
  "lavender": { description: "Aromatic, herbal, and calming. A cornerstone of fougère fragrances and men's perfumery. French lavender from Provence is the most prized, offering a clean, slightly camphorous aroma with a floral sweetness.", category: "Aromatic", origin: "Provence, France", image: "https://images.unsplash.com/photo-1499002238440-d264edd596ec?w=600&q=80" },
  "tobacco": { description: "Warm, sweet, and slightly honeyed. Tobacco notes evoke dried tobacco leaves, pipe tobacco, or cured Virginia leaf. It adds a cozy, sophisticated warmth that pairs wonderfully with vanilla, spices, and leather.", category: "Aromatic", origin: "Cuba, Virginia, Turkey", image: "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=600&q=80" },
  "patchouli": { description: "Earthy, woody, and slightly sweet with a deep, rich character. Patchouli adds remarkable depth and longevity. Dark patchouli is rich and chocolatey, while light patchouli is cleaner and more transparent.", category: "Aromatic", origin: "Indonesia, Philippines", image: "https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=600&q=80" },
  "basil": { description: "Aromatic, green, and slightly anise-like with a fresh, herbal vitality. Basil adds an unexpected freshness to fragrances, bridging the gap between herbs and spices. It works beautifully with citrus and green notes.", category: "Aromatic", origin: "Mediterranean, Asia", image: "https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=600&q=80" },
  "rosemary": { description: "Herbal, camphorous, and woody with a clean, Mediterranean freshness. Rosemary adds an aromatic, slightly medicinal quality that evokes herb gardens and coastal hillsides.", category: "Aromatic", origin: "Mediterranean", image: "https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=600&q=80" },
  "thyme": { description: "Herbal, warm, and slightly medicinal with a dry, green character. Thyme adds an authentic herbal quality to aromatic compositions. It pairs naturally with lavender and other Mediterranean herbs.", category: "Aromatic", origin: "Mediterranean", image: "https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=600&q=80" },
  "mint": { description: "Cool, fresh, and invigorating with an icy clarity. Peppermint is sharp and cooling, while spearmint is sweeter and greener. Mint adds instant freshness and an energizing quality to compositions.", category: "Aromatic", origin: "Americas, Europe", image: "https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=600&q=80" },
  "sage": { description: "Herbal, slightly camphorous, and dry with an aromatic warmth. Clary sage is more floral and has a muscatel, wine-like quality that's prized in perfumery. It adds depth to aromatic and herbal compositions.", category: "Aromatic", origin: "Mediterranean, Europe", image: "https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=600&q=80" },
  "tea": { description: "Clean, astringent, and slightly smoky with a refined, calming quality. Green tea is bright and dewy, black tea is richer and malty, while white tea is soft and delicate. Tea notes add a sophisticated minimalism.", category: "Aromatic", origin: "China, Japan, India", image: "https://images.unsplash.com/photo-1556881286-fc6915169721?w=600&q=80" },
  "green tea": { description: "Bright, clean, and slightly astringent with a dewy, calming quality. Green tea became iconic in perfumery through Elizabeth Arden's Green Tea. It adds a serene, transparent freshness that feels modern and refined.", category: "Aromatic", origin: "China, Japan", image: "https://images.unsplash.com/photo-1556881286-fc6915169721?w=600&q=80" },

  // ── FRUITS ──
  "peach": { description: "Juicy, sweet, and velvety with a soft, fuzzy warmth. Peach adds a lush, feminine fruitiness that bridges fresh and gourmand. The lactone compounds in peach create a creamy, skin-like quality.", category: "Fruity", origin: "China, Mediterranean", image: "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=600&q=80" },
  "apple": { description: "Crisp, fresh, and clean with a green or red character depending on the variety. Green apple is tart and sparkling, while red apple is sweeter. Apple adds a youthful, approachable freshness.", category: "Fruity", origin: "Central Asia, worldwide", image: "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=600&q=80" },
  "pear": { description: "Soft, watery, and clean with a subtle, delicate sweetness. Pear adds a gentle, transparent fruitiness that's less assertive than apple. It creates an airy, feminine quality in fresh compositions.", category: "Fruity", origin: "Europe, Asia", image: "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=600&q=80" },
  "plum": { description: "Rich, dark, and jammy with a wine-like depth. Plum adds a luxurious, slightly decadent fruitiness that works beautifully in oriental and autumnal compositions. It has a velvety, almost boozy quality.", category: "Fruity", origin: "China, Europe", image: "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=600&q=80" },
  "fig": { description: "Green, milky, and slightly coconut-like with a woody warmth. Fig in perfumery captures both the fruit and the leaf — the leaf is greener and more aromatic, while the fruit is sweeter and creamier.", category: "Fruity", origin: "Mediterranean", image: "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=600&q=80" },
  "raspberry": { description: "Tart, sweet, and jewel-like with a vibrant berry character. Raspberry adds a sparkling, slightly powdery fruitiness. The ionone compounds give it a subtle violet-like facet.", category: "Fruity", origin: "Europe, Americas", image: "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=600&q=80" },
  "blackberry": { description: "Dark, juicy, and slightly tart with a wild, hedgerow character. Blackberry adds a rich, deep fruitiness that's less sweet than raspberry. It works beautifully in dark, mysterious compositions.", category: "Fruity", origin: "Europe, Americas", image: "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=600&q=80" },
  "cherry": { description: "Sweet, bright, and slightly almond-like with a juicy, candy-like quality. Cherry can range from tart Morello to sweet Maraschino. It adds a playful, youthful fruitiness often paired with almonds and vanilla.", category: "Fruity", origin: "Europe, Americas, Japan", image: "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=600&q=80" },
  "lychee": { description: "Exotic, floral, and rosy with a translucent sweetness. Lychee bridges the gap between fruit and flower, adding a sophisticated, almost peony-like quality. It's popular in modern feminine fragrances.", category: "Fruity", origin: "China, Southeast Asia", image: "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=600&q=80" },
  "mango": { description: "Tropical, lush, and creamy with a rich, exotic sweetness. Mango adds a sun-drenched, vacation quality to fragrances. It pairs naturally with coconut, vanilla, and tropical flowers.", category: "Fruity", origin: "India, Southeast Asia", image: "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=600&q=80" },
  "pineapple": { description: "Bright, tropical, and juicy with a slightly fermented edge. Pineapple adds a bold, exotic fruitiness. Ethyl maltol and DMHF are key molecules used to create pineapple effects in niche perfumery.", category: "Fruity", origin: "South America, Philippines", image: "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=600&q=80" },
  "pomegranate": { description: "Tart, jewel-like, and slightly tannic with a sophisticated fruitiness. Pomegranate adds a modern, unexpected freshness that works in both fruity and woody compositions.", category: "Fruity", origin: "Iran, Mediterranean", image: "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=600&q=80" },
  "passion fruit": { description: "Exotic, tangy, and tropical with a slightly tart, seductive quality. Passion fruit adds a vibrant, sensual fruitiness. Its unique aroma profile bridges sweet and tart in unexpected ways.", category: "Fruity", origin: "South America", image: "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=600&q=80" },

  // ── GREEN & AQUATIC ──
  "oakmoss": { description: "Earthy, forest-like, and damp with a rich, green complexity. Oakmoss is one of the most important ingredients in chypre fragrances. IFRA restrictions have limited its use, but it remains a beloved note.", category: "Green", origin: "European forests", image: "https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=600&q=80" },
  "moss": { description: "Damp, green, and earthy with a forest-floor quality. Moss notes evoke wet woods and shaded glens. Along with oakmoss, tree moss is used in perfumery to add a natural, outdoorsy depth.", category: "Green", origin: "Various forests", image: "https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=600&q=80" },
  "grass": { description: "Fresh, green, and slightly sweet with a just-cut-lawn quality. Grass notes add a natural, outdoor freshness that's lively and vibrant. It creates an impression of open fields and summer days.", category: "Green", origin: "Synthetic accord", image: "https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=600&q=80" },
  "seaweed": { description: "Marine, iodine-like, and salty with an oceanic depth. Seaweed notes add a distinctive coastal character that goes beyond generic 'aquatic' accords. It creates a raw, natural marine quality.", category: "Aquatic", origin: "Coastal regions", image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=600&q=80" },
  "sea salt": { description: "Mineral, crisp, and briny with a skin-like warmth. Sea salt notes add a natural, effortless quality that evokes ocean air and sun-kissed skin. Very popular in modern clean and aquatic fragrances.", category: "Aquatic", origin: "Synthetic accord", image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=600&q=80" },

  // ── MISCELLANEOUS ──
  "iso e super": { description: "A modern synthetic molecule that creates a smooth, velvety, woody-amber aura. Often described as a 'your skin but better' effect — it has a chameleon-like quality, smelling slightly different on every wearer. The backbone of many modern hits.", category: "Synthetic", origin: "Laboratory", image: "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=600&q=80" },
  "ambroxan": { description: "A powerful synthetic that recreates ambergris — warm, mineral, slightly salty with incredible projection. It creates a luminous, skin-like halo. The molecule behind Dior Sauvage's massive sillage and many modern blockbusters.", category: "Synthetic", origin: "Laboratory", image: "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=600&q=80" },
  "cashmeran": { description: "Warm, musky, and woody with a cozy, fabric-like quality. Cashmeran evokes cashmere sweaters and intimate warmth. It adds a soft, enveloping comfort that's become essential in cozy, skin-scent fragrances.", category: "Synthetic", origin: "Laboratory", image: "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=600&q=80" },
};

export default NOTE_ENCYCLOPEDIA;
